### ISSUE TITLE
在家里重置电脑一不小心把整部电脑两个硬盘全部清空了，今晚哭晕在厕所，我所有文件包括照片都没了

### ISSUE THREAD

**Issue by zhangchuanjia123** [lgfy/learn_github#17]
![222](https://cloud.githubusercontent.com/assets/18108847/14405632/91ba3cc6-fec5-11e5-8f80-c3c33f23aa38.png)

**Comment by huigewang** [comment]
整合硬盘恢复工具应该可以恢复的

**Comment by zhangchuanjia123** [comment]
都已经完全删掉了没有缓存空间怎么恢复哦 @huigewang

**Comment by jiazil** [comment]
基本上可以无救了
